IMA-10467 - Add converter from txt to JSON for appthinningreport
ChargePoint/xcparse pull request #57
Opened 2021-04-05 21:43 UTC by vshaweddy-cpi

**Change Description:**
Convert app thinning report.txt to json file
**Test Plan/Testing Performed:**
Run using xcode

2021-04-07 18:31 UTC, vshaweddy-cpi commented
Scheme settings
![Screen Shot 2021-04-06 at 12 03 22 PM](https://user-images.githubusercontent.com/79033214/113916362-e1e5c400-97ad-11eb-940e-8cf46cb0dbc5.png)

2021-04-13 23:11 UTC, mgorkani-cpi requested changes

2021-04-14 15:04 UTC, vshaweddy-cpi commented on Sources/Converter/Helper/MemorySize.swift
> +        case 1_024..<(1_024 * 1_024 * 1_024):
The first condition 1_024..<(1_024 * 1_024) will force the third condition to be (1_024*1_024)..<(1_024 * 1_024 * 1_024). But I also update it to be more concise.

2021-04-20 08:29 UTC, masumh commented
{"export_url":"https://github.com/settings/security-log/export.json?token=6127babc-b98d-4664-8d00-95581e5195c1","job_url":"https://github.com/_jobs/6127babc-b98d-4664-8d00-95581e5195c1"}

2021-04-20 08:31 UTC, masumh commented on Package.swift
> +            dependencies: []),
.target(
            name: "Converter",
            dependencies: []),

2021-04-20 08:34 UTC, masumh approved these changes

2021-04-20 08:35 UTC, masumh commented
https://github.com/ChargePoint/xcparse/pull/57#issue-609242851

2021-04-20 08:45 UTC, masumh approved these changes
https://github.com/ChargePoint/xcparse/pull/57#issue-609242851

2021-04-20 08:48 UTC, masumh approved these changes
https://github.com/ChargePoint/xcparse/pull/57#issue-609242851

2021-04-20 08:48 UTC, masumh commented
https://github.com/ChargePoint/xcparse/pull/57#issue-609242851

2022-01-27 13:26 UTC, closed without merging

2022-01-27 13:27 UTC, rsukumar-cpi commented
Picked up these changes and created a new PR #73.