Add `--legacy` flag for Xcode 16 compatibility
ChargePoint/xcparse pull request #88
Opened 2024-09-13 08:38 UTC by marinofelipe

**Change Description:**

As discussed in #87. This is a short term solution, for a long term one the `xcresulttool` usage is to be later reviewed.

**Test Plan/Testing Performed:**

I didn't find tests covering the `xcresulttool` command that is generated to extend asserting for the presence of `--legacy`, but please let me know if there's one or if I should write a test for it.

2024-09-17 23:56 UTC, FPVMateOfficial commented
Worked for me (macOS Sonoma 14.6.1 / Xcode 16)

Thanks for the quick fix!

2024-10-03 18:54 UTC, dailydmello commented
Can this PR be reviewed and merged, as I am facing this problem aswell

2024-10-05 13:01 UTC, marinofelipe commented
> Can this PR be reviewed and merged, as I am facing this problem aswell

@abotkin-cpi could you please take a look? Let me know if there's anything missing, such as extending the tests. Thank you

2024-10-10 18:12 UTC, tahirmt commented
I think this change will break compatibility with Xcode 15. Perhaps the `--legacy` flag should be conditionally added instead.

2024-10-10 22:49 UTC, rsukumar-cpi requested changes
Thanks for raising this PR @marinofelipe!
As mentioned by @tahirmt, the `--legacy` flag is not supported by older versions of xcresulttool (Xcode 15 and below). We should conditionally add the `--legacy` flag if the xcresulttool version being used is greater than or equal to 23028 (xcresultool version for Xcode 16 command line tools). You can look at the usage of `xcresulttoolCompatibleWithUnicodeExportPath()` in the `Version` extension as an example of a similar version check.

2024-10-10 23:14 UTC, abotkin-cpi commented
Hey @marinofelipe, sorry I've been out this last month for my wedding & honeymoon. As @tahirmt mentioned and @rsukumar-cpi from our ChargePoint team confirmed in testing, we'll need to add backwards compatibility support prior to merging due to the limitations of older xcresulttool. If you have the chance to add it, that would be awesome, otherwise I'll take a stab at adding it to your PR when I'm free this weekend.

2024-10-12 14:16 UTC, marinofelipe commented
@abotkin-cpi , @rsukumar-cpi [afad1f](https://github.com/ChargePoint/xcparse/pull/88/commits/8afad1fe169204038bb0a7e98ab5a191b6332df1) adds the condition. Some observations
- To resolve the condition only once I've used a private let (a private global var). It could be done in other ways like a static var on the `XCResultToolCommand` type, etc. I used the approach I found cleaner, but let me know in case you have other preferences, or feel free to do changes/commit on top of it.
- I tested locally with both the Xcode 15.* and 16 toolchains and the logic looks correct
- No idea why the CI test failed, I can't see much besides "Xcode Test for Mac (failed)". Locally they pass on both Xcode 15.4 and 16.0. Tested on macOS 15.0 (Sequoia)

2024-10-14 20:03 UTC, rsukumar-cpi approved these changes

2024-10-14 20:04 UTC, rsukumar-cpi commented
@marinofelipe The changes look good to me. I'm looking into the failing tests in our CI right now. Once the issue is resolved, I will merge this PR.

2024-10-24 03:16 UTC, tahirmt commented
@rsukumar-cpi any idea when we can get this released?

2024-10-24 23:47 UTC, merged

2024-10-28 22:17 UTC, rsukumar-cpi commented
@tahirmt @marinofelipe Just pushed a release 2.3.2 with this change. You should be able to install the latest version via `brew`.